# blink example for Arduino uno based on the
# https://github.com/sudar/Arduino-Makefile

BOARD_TAG = uno
ARDMK_DIR = /usr/share/arduino
ARDUINO_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr

include $(ARDUINO_DIR)/Arduino.mk
